import { formatWorkPeriod } from "@/utils";
import { icons } from "../TechCarousel/Icons";

export const WorkData = [
  {
    company: "Ambra",
    role: "Full Stack Developer",
    period: formatWorkPeriod("2022-01"),
    location: "São Paulo, SP, Brazil | Remote",
    responsibilities: [
      "Developed and maintained full-stack applications for accounting solutions",
      "Collaborated with cross-functional teams using Scrum methodologies",
      "Integrated APIs to connect front-end and back-end services",
      "Reviewed and validated pull requests to ensure code quality and adherence to best practices",
      "Tested tasks and features to verify functionality and prevent regressions",
      "Wrote and maintained automated feature tests to validate business-critical functionality",
    ],
    stack: [
      icons.angular,
      icons.css,
      icons.docker,
      icons.git,
      icons.html,
      icons.laravel,
      icons.mongodb,
      icons.mysql,
      icons.php,
      icons.scrum,
      icons.tailwind,
      icons.typescript,
    ],
  },
  {
    company: "Guardiã Digital",
    role: "Full Stack Developer",
    period: formatWorkPeriod("2019-05", "2021-11"),
    location: "São José do Rio Preto, SP, Brazil | On-site",
    responsibilities: [
      "Built and maintained digital document management systems",
      "Optimized legacy applications and improved usability",
      "Integrated APIs to connect front-end and back-end services",
      "Collaborated on multiple projects, adapting quickly to different business requirements and technologies.",
    ],
    stack: [
      icons.angular,
      icons.bootstrap,
      icons.css,
      icons.docker,
      icons.express,
      icons.git,
      icons.html,
      icons.javascript,
      icons.laravel,
      icons.linux,
      icons.mongodb,
      icons.node,
      icons.php,
      icons.postgresql,
      icons.regex,
      icons.sql,
      icons.typescript,
    ],
  },
];
