import { formatWorkPeriod } from "@/utils";
import { icons } from "../../../Icons";

export const WorkData = [
  {
    company: "Ambra",
    role: "Full Stack Developer - (Mid-Level)",
    period: formatWorkPeriod("2022-01", "2026-03"),
    location: "São Paulo, SP, Brazil | Remote",
    language: "Portuguese",
    responsibilities: [
      "Developed and maintained features in a microservices architecture using Laravel, Angular, and Python.",
      "Integrated microservices (payments, notifications, communication) using RabbitMQ.",
      "Designed and implemented data structures with MySQL and MongoDB, including migrations and queryoptimization.",
      "Participated in architecture decisions, contributing to scalability and service organization.",
      "Performed code reviews and refactoring of legacy code, improving performance and maintainability.",
      "Identified and fixed complex bugs in distributed systems, ensuring application stability.",
      "Collaborated in an agile team using Scrum methodology.",
      "Worked with cloud services using Azure, supporting application deployment and maintenance.",
    ],
    stack: [
      icons.python,
      icons.angular,
      icons.css,
      icons.docker,
      icons.git,
      icons.html,
      icons.laravel,
      icons.mongodb,
      icons.mysql,
      icons.php,
      icons.scrum,
      icons.tailwind,
      icons.typescript,
      icons.azure,
    ],
  },
  {
    company: "Guardião Digital",
    role: "Full Stack Developer - (Mid-Level)",
    period: formatWorkPeriod("2019-05", "2021-11"),
    location: "São José do Rio Preto, SP, Brazil | On-site",
    language: "Portuguese",
    responsibilities: [
      "Developed and maintained monolithic applications using Laravel and Angular.",
      "Participated in rewriting a legacy Flash application into a modern architecture using Angular and Laravel.",
      "Worked extensively with SQL, analyzing and optimizing complex queries and database functions.",
      "Debugged legacy systems, identifying and fixing issues in critical functionalities.",
      "Developed solutions using plain PHP as well as frameworks, adapting to different system contexts.",
      "Worked on multiple projects simultaneously, implementing new features and fixing bugs.",
      "Built image processing solutions for data analysis automation using specialized libraries.",
      "Developed image processing pipelines using OpenCV for automated data analysis.",
    ],
    stack: [
      icons.angular,
      icons.bootstrap,
      icons.css,
      icons.docker,
      icons.express,
      icons.git,
      icons.html,
      icons.javascript,
      icons.laravel,
      icons.linux,
      icons.mongodb,
      icons.node,
      icons.php,
      icons.postgresql,
      icons.regex,
      icons.sql,
      icons.typescript,
    ],
  },
  {
    company: "Act Like You Matter",
    role: "Volunteer Frontend Developer",
    period: formatWorkPeriod("2025-05", "2025-07"),
    location: "San Diego, CA, United States | Remote",
    language: "English",
    responsibilities: [
      "Collaborated with an international team in English-speaking meetings and asynchronous communicationvia Slack, contributing to technical and strategic decisions.",
      "Engineered interactive, animated front-end components and code prototypes for a dynamic character UI, leveraging physics-based or frame-based layout movements as a Proof of Concept.",
    ],
    stack: [
      icons.css,
      icons.git,
      icons.html,
      icons.tailwind,
      icons.typescript,
      icons.react,
      icons.nextjs,
      icons.figma,
    ],
  },
];
