import { formatWorkPeriod } from "@/utils";
import { icons } from "../../../Icons";

export const WorkData = [
  {
    company: "Ambra",
    role: "Full Stack Engineer",
    period: formatWorkPeriod("2022-01", "2026-03"),
    location: "São Paulo, SP, Brazil | Remote",
    language: "Portuguese",
    responsibilities: [
      "Architected and developed scalable microservices using Python (FastAPI) and PHP (Laravel) within a distributed Docker-based environment.",
      "Built Angular front-end applications integrated with asynchronous microservices using RabbitMQ, supporting complex distributed workflows.",
      "Collaborated in code reviews, testing, architecture discussions, and technical decision-making within Agile teams.",
      "Managed MySQL, MongoDB, and AWS S3 integrations for scalable document processing and distributed data handling.",
      "Investigated and resolved complex cross-service production issues through deep debugging, reverse engineering, and analysis of legacy and distributed systems.",
      "Developed unit tests and contributed to the evolution and maintenance of large-scale applications with minimal supervision.",
    ],
    stack: [
      icons.python,
      icons.angular,
      icons.css,
      icons.docker,
      icons.git,
      icons.html,
      icons.laravel,
      icons.mongodb,
      icons.mysql,
      icons.php,
      icons.scrum,
      icons.tailwind,
      icons.typescript,
      icons.azure,
    ],
  },
  {
    company: "Guardião Digital",
    role: "Full Stack Engineer",
    period: formatWorkPeriod("2019-05", "2021-11"),
    location: "São José do Rio Preto, SP, Brazil | On-site",
    language: "Portuguese",
    responsibilities: [
      "Contributed to the modernization of a large legacy Flash application into a modern Angular + Laravel platform with redesigned architecture and UI.",
      "Developed and maintained complex business-critical features, APIs, Angular components, and PostgreSQL queries/functions across multiple large-scale applications.",
      "Independently led standalone projects, handling architecture, backend development, database design, debugging, deployments, and production support with minimal supervision.",
      "Troubleshot undocumented legacy systems, resolved complex production issues, and maintained legacy AngularJS/Angular 2 applications during modernization initiatives.",
    ],
    stack: [
      icons.angular,
      icons.bootstrap,
      icons.css,
      icons.docker,
      icons.express,
      icons.git,
      icons.html,
      icons.javascript,
      icons.laravel,
      icons.linux,
      icons.mongodb,
      icons.node,
      icons.php,
      icons.postgresql,
      icons.regex,
      icons.sql,
      icons.typescript,
    ],
  },
  {
    company: "Act Like You Matter",
    role: "Volunteer Frontend Developer",
    period: formatWorkPeriod("2025-05", "2025-07"),
    location: "San Diego, CA, United States | Remote",
    language: "English",
    responsibilities: [
      "Collaborated with an international team in English-speaking meetings and asynchronous communicationvia Slack, contributing to technical and strategic decisions.",
      "Engineered interactive, animated front-end components and code prototypes for a dynamic character UI, leveraging physics-based or frame-based layout movements as a Proof of Concept.",
    ],
    stack: [
      icons.css,
      icons.git,
      icons.html,
      icons.tailwind,
      icons.typescript,
      icons.react,
      icons.nextjs,
      icons.figma,
    ],
  },
];
